/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "server.h"

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->name))
		 return FALSE;
	return TRUE;
}
